sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jackyxu/docker_practice -f Dockerfile.dev .

scripts:
  - docker run -e CI=true jackyxu/docker_practice npm run test -- --coverage
