sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jackyxu/docker_practice -f Dockerfile.dev .

scripts:
  - docker run -e CI=true jackyxu/docker_practice npm run test -- --coverage

deploy:
  provider: firebase
  token:
    secure: "1//01QaCswrK88a-CgYIARAAGAESNwF-L9IrOfFHMiOcns2j-KAyQAF2C7cN9CdI_8iPz3gLJ1gy1Lp1ENZY_hoUnA5Psl3-BaCJPCE"
  message: "deployed to firebase"
  on:
    branch: master